-- 1. 系统管理员表
CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(100) NOT NULL,
  `nickname` VARCHAR(50) DEFAULT NULL,
  `status` TINYINT DEFAULT 1,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. AI工具信息表
CREATE TABLE IF NOT EXISTS `tool_info` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tool_code` VARCHAR(50) NOT NULL UNIQUE,
  `tool_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `status` TINYINT DEFAULT 1,
  `icon` VARCHAR(100) DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. 工具独立大模型配置表
CREATE TABLE IF NOT EXISTS `tool_config` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `tool_code` VARCHAR(50) NOT NULL,
  `config_key` VARCHAR(50) NOT NULL,
  `config_value` TEXT NOT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_tool_key` (`tool_code`, `config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. 系统全局配置表 (网页端可设置全局 Key)
CREATE TABLE IF NOT EXISTS `sys_config` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `config_key` VARCHAR(100) NOT NULL UNIQUE,
  `config_value` TEXT NOT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. MCP 独立进程服务配置表
CREATE TABLE IF NOT EXISTS `sys_mcp_server` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `server_name` VARCHAR(100) NOT NULL UNIQUE,
  `transport_type` VARCHAR(20) NOT NULL,
  `command` VARCHAR(255) DEFAULT NULL,
  `args` VARCHAR(500) DEFAULT NULL,
  `env_vars` TEXT DEFAULT NULL,
  `sse_url` VARCHAR(255) DEFAULT NULL,
  `tool_code` VARCHAR(50) NOT NULL,
  `status` TINYINT DEFAULT 1,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. 临时物理文件清理记录表
CREATE TABLE IF NOT EXISTS `core_temp_file` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `file_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `tool_code` VARCHAR(50) NOT NULL,
  `status` TINYINT DEFAULT 0,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_status_createtime` (`status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
